import os
import datetime
from scripts.resources import Resources
from scripts.barcodes import Barcodes
from scripts import general_functions as utils
from snakemake.utils import min_version

# set minimum snakemake version
min_version("8.13.0")

# load config file
configfile: "config/config.yaml"

# load genome resources
resources = Resources(config["genome"], 
                      config["ensembl_genome_build"])








        
# Save snakemake terminal output to log file
time = datetime.datetime.now().strftime("%Y-%m-%d_%H-%M-%S")
snake_log = f"logs/snakemake/{time}_snakemake.log"
os.makedirs("logs/snakemake", exist_ok=True)

onsuccess: 
    shell("cp -v {log} {snake_log}")
    print("Analysis finished successfully!")
onerror:
    shell("cp -v {log} {snake_log}")
    print(f"Analysis failed...")

