genome: hg38
ensembl_genome_build: "110"
barcode_length: 8
STAR:
  extra: ""
bigwig:
  binSize: 1
  normalise: CPM
resources: # computing resources
  trim:
    cpu: 8
    time: 60
  fastqc:
    cpu: 4
    time: 60
  index:
    cpu: 36
    time: 60
  star_index:
    cpu: 36
    time: 60
  mapping:
    cpu: 12
    time: 120
  samtools:
    cpu: 4
    time: 30
  deeptools:
    cpu: 6
    time: 60
  pureclip:
    cpu: 12
    time: 120
  plotting:
    cpu: 2
    time: 20
